# Generated by Django 2.1.2 on 2019-02-10 06:00

import awards.models
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('slug', models.SlugField(max_length=144)),
                ('description', models.TextField(max_length=600)),
                ('image_cover', models.ImageField(null=True, upload_to=awards.models.user_directory_path)),
                ('nominator', models.CharField(max_length=144)),
                ('nomination_comments', models.TextField(max_length=1200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('site', models.CharField(default='GLS', max_length=144)),
                ('interviewee', models.CharField(max_length=144)),
                ('interviewee_contact', models.EmailField(max_length=144)),
                ('question', models.CharField(max_length=144)),
                ('file_id', models.CharField(blank=True, max_length=149, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('featured', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
